### PR TITLE
Fix regex for finding 004 projects and update README

### LINKED ISSUE #14: Readme - explain reason for behaviour
Update readme to explain why:
> If this is > 1, the upload_and_test job will not be run and the workflow will end

It might not be obvious to someone else why it works in this way

### PR DESCRIPTION
**Pull request by rklocke**
- Fix regex to find a 004 test project with the config file in the name, which I broke in the last PR with f string :)
- Update README with some wording changes (fixes #14)

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/15)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/15)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`.github/workflows/get_or_create_testing_project.py` line 159 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/15#-O6_T6jg-rSaSllapxdV:-O6_T6jg-rSaSllapxdW:b-d8psjh) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/bea64dd04fc97c4dafc10b21ab62daefb9bb68bb/.github/workflows/get_or_create_testing_project.py#L159)):*
> ```Python
>             dx.find_projects(
>                 name=(
>                     f'^004_[\d]{2}[\d]{2}[\d]{2}_{prefix}'
> ```

do you have a load of test cases for this regex?

if you're mocking `dx.find_projects` you can check the call_args of each invocation to test the regex string to `name` is as expected



_Code quote:_
```Python
f'^004_[\d]{2}[\d]{2}[\d]{2}_{prefix}'
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/15)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`.github/workflows/get_or_create_testing_project.py` line 159 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/15#-O6_T6jg-rSaSllapxdV:-O6_dC2K1fw_1zh9r97-:b-jvf7ys) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/bea64dd04fc97c4dafc10b21ab62daefb9bb68bb/.github/workflows/get_or_create_testing_project.py#L159)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do you have a load of test cases for this regex?

if you're mocking `dx.find_projects` you can check the call_args of each invocation to test the regex string to `name` is as expected
</blockquote></details>

Added unit tests that regex is passed to `dx.find_projects` as expected in development mode and not - is this okay or are there other tests I should be adding?

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/15#-:-O6_qaE56J1Zoy6dcCrD:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/15)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
