### PR TITLE
IN-722 Get or create 004 test project

### PR DESCRIPTION
**Pull request by rklocke**
- Now has extra script which finds an existing 004 test project for the config file which has been updated in the PR or creates a new one
- Uploads the updated config file to that 004 project (instead of a static 003 proj)
- Updated `get_production_config.py` to handle dias batch configs rather than conductor configs for this first version (so added an example TWE config and removed the example conductor config)
- Creates nicer diff report which is wider with 3 lines of context

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/3)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`get_or_create_testing_project.py` line 158 at r2](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/3#-O37oTVp0txtAeHmb1pn:-O37oTVp0txtAeHmb1po:b-z5nbnw) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/b7fad05c65cd7e2de21c4b132ea3bc8e8d116186/get_or_create_testing_project.py#L158)):*
> ```Python
>                 ),
>                 description=(
>                     "This project was created automatically by GitHub Actions"
> ```

can we generate a URL to the action that created the project for provenance?

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/3)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`get_or_create_testing_project.py` line 158 at r2](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/3#-O37oTVp0txtAeHmb1pn:-O37zlAi5ix-6j9_LJyD:b-p4eslu) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/b7fad05c65cd7e2de21c4b132ea3bc8e8d116186/get_or_create_testing_project.py#L158)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we generate a URL to the action that created the project for provenance?
</blockquote></details>

Added :)

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/3)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/3#-:-O38EOlo680xDm739GeM:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
