### PR TITLE
IN-727 Copy test data to project and check jobs complete successfully

### PR DESCRIPTION
**Pull request by rklocke**
- A step is added (`Copy test data to test project`) which, based on a job ID for the assay (CEN or TWE) given in the repository's GitHub Actions variables, copies over the Dias single folder from the 002 project to our 004 test project (because eggd_artemis fails if files are not in the same project where it's run :upside_down_face:)
  - If this has been copied into the project (i.e. from a previous workflow run or manually) then it just moves the files into the folder for the current GitHub Actions workflow run
- Adds step (`Check jobs complete successfully`) to hold the workflow to check that all jobs which have been launched by the eggd_dias_batch job complete successfully
- Modified the YML workflow file so the workflow can be run from another repository using `on: workflow_call` (i.e. keeping the workflow in this repo and calling it from a repo for a batch config file)
  - Now takes input of secret variable (i.e. DX_TOKEN) as this can't just be set in the caller repository, and steps to check out code of both repos (so it can access the changed JSON config file in the caller repo, and Python scripts in this repo)
- Workflow now adds extra comments to the PR for:
  - The config file updated in the PR being uploaded to DNAnexus (with a URL link to it)
  - The diff report being created (and a URL link to download it)
  - The eggd_dias_batch job being set off in DNAnexus (with a URL link to it)
- Adds beginning of a README to list variables and secrets required
- Weirdly it thinks I've deleted and made a new run_testing_jobs.py, but only small changes made so that a CNV calling job ID can be given if `RUN_CNV_CALLING` repository variable is set to `False`

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/7)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/7)* status: all files reviewed, 2 unresolved discussions (waiting on @rklocke)

___
*[`README.md` line 9 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/7#-O4tN1sL3qA_wav3H4cB:-O4tN1sM8ojGBvyhYCKZ:b-jh3oj5) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/eb4021241dda4102bc442b3007b36f4fa6c4098d/README.md#L9)):*
> ```Markdown
> - Checks if any configuration files (*.JSON files) are updated within the PR.
> - If one configuration file has been updated, the tool:
>   - Looks for a 004 project (with any date) which has the name of the updated configuration file in the project name. If this does not exist, one is created, including the date the PR is opened.
> ```

is it going to use an existing one?
___
*[`README.md` line 31 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/7#-O4tNJei7JbVbuLEnxTw:-O4tNJei7JbVbuLEnxTx:b-gzqkdk) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/eb4021241dda4102bc442b3007b36f4fa6c4098d/README.md#L31)):*
> ```Markdown
> | --- | --- | --- | --- |
> | CONFIG_PATH  | `str` | `project-Fkb6Gkj433GVVvj73J7x8KbV:/dynamic_files/dias_batch_configs` | The path in 001_Reference where production configuration files are stored |
> | PROD_JOBS  | `str` | `'{"TWE": "job-GpfQ2fQ4fj3XG67xkbPFXKZg","CEN": "job-Gpbq1q847X23zF1568K3x3q8"}'` | Jobs which were run in production 002 projects for each assay which can be used for testing to re-run with the updated configuration file |
> ```

i assume that those job ids might need updating when the time comes ?

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/7)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`README.md` line 9 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/7#-O4tN1sL3qA_wav3H4cB:-O4tYFMlE8r_xB1eIzu4:b3xlgqs) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/eb4021241dda4102bc442b3007b36f4fa6c4098d/README.md#L9)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is it going to use an existing one?
</blockquote></details>

Clarified that the existing one will be used for testing or a new one made for testing
___
*[`README.md` line 31 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/7#-O4tNJei7JbVbuLEnxTw:-O4tYLdbBbXOOaoNaroZ:bl7sch3) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/eb4021241dda4102bc442b3007b36f4fa6c4098d/README.md#L31)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i assume that those job ids might need updating when the time comes ?
</blockquote></details>

I've listed these job IDs just as an example of the formatting of PROD_JOBS in the README, but these should probably be updated for deployment - will add this in the GitHub issue I've opened :)

**Comment by rklocke** [comment]
Manually cancelled workflow run as only README updated

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
