### PR TITLE
Initial work - integration testing workflow

### PR DESCRIPTION
**Pull request by rklocke**
- Workflow gets the config JSON file which has been changed in the PR, uploads it to DNAnexus test project
- The file ID is provided as input to Python script which finds and returns the related production config version for that assay in 001_Reference so that we can later run jobs for the updated and prod configs and compare outputs

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @rklocke)

___
*[`perform_testing.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1#-O0hfcT79aMID9Jy3O8_:-O0hfcT79aMID9Jy3O8a:b-6h6y6q) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/70723cbe80a8fdd40a783b9eed53fa8826d56e3f/perform_testing.py#L13)):*
> ```Python
>     """
>     Parse command line arguments
> ```

missing param
___
*[`requirements.txt` line 1 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1#-O0hgEbF98WLSSDUfl9X:-O0hgEbF98WLSSDUfl9Y:bp0mq5l) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/70723cbe80a8fdd40a783b9eed53fa8826d56e3f/requirements.txt#L1)):*
> ```help
> dxpy==0.365.0
> ```

0.378.0 exists



_Code quote:_
```help
0.365.0
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`perform_testing.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1#-O0hfcT79aMID9Jy3O8_:-O0rdOhaBD5amIk5tpfk:b-896fix) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/70723cbe80a8fdd40a783b9eed53fa8826d56e3f/perform_testing.py#L13)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing param
</blockquote></details>

Done.
___
*[`requirements.txt` line 1 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1#-O0hgEbF98WLSSDUfl9X:-O0rdPWE77hG1ej198Av:b-896fix) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/70723cbe80a8fdd40a783b9eed53fa8826d56e3f/requirements.txt#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

0.378.0 exists
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1)* status: all files reviewed, 2 unresolved discussions (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
