### PR TITLE
IN-675 Compare changed config to prod config

### PR DESCRIPTION
**Pull request by rklocke**
- Separates workflow into two separate jobs
  - The first job detects if any config files are changed in the PR
  - The second runs all downstream steps only if first job is true
- New steps in second job
  - One step to create and write out dictionary to JSON file containing info on config updated in PR and prod config in 001_Reference
  - Another step retrieves config info with jq and uses this to produce diff report comparing newly updated with prod config in 001_Reference, uploads this HTML file as artifact of workflow

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/2)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`.github/workflows/test_changes.yml` line 41 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/2#-O2Uv61Y-mqhsQSig0FJ:-O2Uv61Z3irvhwi6Dq4x:bfja3p6) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/97e75ca18cab36606d30d0e9945d138a0fdf9cee/.github/workflows/test_changes.yml#L41)):*
> ```YAML
>           python -m pip install --upgrade pip
>           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
>           sudo apt-get install -y aha
> ```

 ... what is this?



_Code quote:_
```YAML
sudo apt-get install -y aha
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/2)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`.github/workflows/test_changes.yml` line 41 at r1](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/2#-O2Uv61Y-mqhsQSig0FJ:-O2UvTJP9kABVrrH0ztg:b2bwxww) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/97e75ca18cab36606d30d0e9945d138a0fdf9cee/.github/workflows/test_changes.yml#L41)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

... what is this?
</blockquote></details>

oh it's a package which made it easy to output the diff info with colours to a HTML file.. is there a better way to do this?

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
