### PR TITLE
IN-746 Unit testing 1

### PR DESCRIPTION
**Pull request by rklocke**
- Add unit tests for:
  - get_production_config.py
  - get_or_create_testing_project.py
  - check_jobs_complete.py
- Small formatting changes to print statements for unit tests
- Add .coveragearc, .gitignore and pytest.ini to configure tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11)

### CODE REVIEW

**Review by jethror1 — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11)* status: 7 of 10 files reviewed, all discussions resolved

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @rklocke)

___
*[`.github/workflows/tests/test_check_jobs_complete.py` line 21 at r2](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11#-O5mn8ErCcnM4cvGynG2:-O5mn8ErCcnM4cvGynG3:bz2udl9) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/b4eacefb9060f2eda27532cddc196c30ba510d70/.github/workflows/tests/test_check_jobs_complete.py#L21)):*
> ```Python
>     Tests for the DXManage.wait_on_done() function which waits until all jobs
>     which are launched by the job set off by the workflow (eggd_dias_batch)
>     complete successfully
> ```

assume this is a copy paste error?



_Code quote:_
```Python
    Tests for the DXManage.wait_on_done() function which waits until all jobs
    which are launched by the job set off by the workflow (eggd_dias_batch)
    complete successfully
```
___
*[`.github/workflows/tests/test_check_jobs_complete.py` line 119 at r2](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11#-O5mna6y-fbyOVmyvAjJ:-O5mna6y-fbyOVmyvAjK:b403ong) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/b4eacefb9060f2eda27532cddc196c30ba510d70/.github/workflows/tests/test_check_jobs_complete.py#L119)):*
> ```Python
>         assert 'All testing jobs set off successfully' in stdout, (
>             'Script not waiting until jobs complete'
>         )
> ```

how does this test that the function waits? would it not be better to just assert that `wait_on_done()` is actually called from your mock?



_Code quote:_
```Python
        _, _ = self.dx_manage.get_job_output_details()

        stdout = self.capsys.readouterr().out

        assert 'All testing jobs set off successfully' in stdout, (
            'Script not waiting until jobs complete'
        )
```
___
*[`.github/workflows/tests/test_get_or_create_testing_project.py` line 139 at r2](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11#-O5mpJ3HAEO7En_7IhPc:-O5mpJ3IAb3nbXhDQ1CZ:b5lgqyr) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/b4eacefb9060f2eda27532cddc196c30ba510d70/.github/workflows/tests/test_get_or_create_testing_project.py#L139)):*
> ```Python
>         self.capsys = capsys
> 
>     @patch('get_or_create_testing_project.dx.DXProject')
> ```

since all tests use this patch you can either patch the class, or add it to your setUp function, or just ignore me and leave it :smile: 



_Code quote:_
```Python
@patch('get_or_create_testing_project.dx.DXProject')
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`.github/workflows/tests/test_check_jobs_complete.py` line 21 at r2](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11#-O5mn8ErCcnM4cvGynG2:-O5r59g42CGyWa5MEcGN:b-w3ztlw) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/b4eacefb9060f2eda27532cddc196c30ba510d70/.github/workflows/tests/test_check_jobs_complete.py#L21)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

assume this is a copy paste error?
</blockquote></details>

Oopsie, fixed
___
*[`.github/workflows/tests/test_check_jobs_complete.py` line 119 at r2](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11#-O5mna6y-fbyOVmyvAjJ:-O5r5Ihe6Eo1mYzTuFUS:bxnw02m) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/b4eacefb9060f2eda27532cddc196c30ba510d70/.github/workflows/tests/test_check_jobs_complete.py#L119)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

how does this test that the function waits? would it not be better to just assert that `wait_on_done()` is actually called from your mock?
</blockquote></details>

Updated test, changed set up of tests and used subTest instead of running the same function with the same inputs multiple times
___
*[`.github/workflows/tests/test_get_or_create_testing_project.py` line 139 at r2](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11#-O5mpJ3HAEO7En_7IhPc:-O5r5NQ7CNGoIkqpG5ir:bi4m0gb) ([raw file](https://github.com/eastgenomics/GitHub_Actions/blob/b4eacefb9060f2eda27532cddc196c30ba510d70/.github/workflows/tests/test_get_or_create_testing_project.py#L139)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

since all tests use this patch you can either patch the class, or add it to your setUp function, or just ignore me and leave it :smile:
</blockquote></details>

patched class :)

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/GitHub_Actions/11)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
